### PR TITLE
Fix #29 - latest angular2.d.tsd

### LINKED ISSUE #29: old angular2 type definition - tsc won't compile
tsd.json references old angular2 type definitions:
- `angular/di` module is missing

**Fix:**
- udpate tsd.json with latest angular2

### PR DESCRIPTION
**Pull request by Hotell**
- bumps to latest ( working ) angular2.d.tsd type definition
- fixes module type string in tsconfig.json

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
I'm not actually by a proper computer, but @alexeagle does this seem to be appropriate given your recent changes?

**Comment by alexeagle** [comment]
LGTM
Having the latest angular2.d.ts is certainly required.

Related: There was also a comment about why we use the `///<reference />` given that the compiler can find it from the tsconfig.json. I haven't checked if that works in all tools (eg VSCode intellisense.)

**Comment by Hotell** [comment]
yup, intellisense works in VSCode without `///<reference>`

**Comment by DanielRosenwasser** [comment]
VS itself will work without it as well, @paulvanbrenk should know when this will officially be going out.

Thanks @alexeagle and thanks for the PR @Hotell!

**Pull request merged**
