### PR TITLE
Update demo for angular alpha22

### PR DESCRIPTION
**Pull request by alexeagle**
We no longer need to distribute angular or its typings in the repository.

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
Thanks @alexeagle - going to wait on the DefinitelyTyped PR before I pull this in.

**Comment by alexeagle** [comment]
It's merged.

**Comment by alexeagle** [comment]
ping! I'd like to publish something that references this.

**Comment by DanielRosenwasser** [comment]
Thanks @alexeagle!

**Comment by alexeagle** [comment]
hrm, the readme doesn't format well - sorry about that. Missing the closing triple-backticks in the build section. Want to fix or I can send another PR for it?

**Pull request merged**
