### PR TITLE
Fix #3 - Implement filtering for All, Active, Completed buttons

### LINKED ISSUE #3: Active and Completed Buttons not filtering
Filtering(active, completed) not working

chome 41.0.2272.76 m

baa2d8d8f27798540f884f3cde5de2eaf1119618

### PR DESCRIPTION
**Pull request by mariannemyers**
In lieu of a router, implement filtering for todos by binding to the
click event and calling a function to set a boolean todoFilter.  Use
the todoFilter to hide to the todos.

### CODE REVIEW

**Comment by remojansen** [comment]
I would like to suggest that it would be great to add the new Router and observe URL changes to trigger the filter functions when `#/actives` `#/completed` instead of using event handlers. A lot of people is wondering how to use the new Router and this example could help many of them.

**Comment by mprobst** [comment]
FYI these changes look good to me (from an Angular POV).

**Comment by mhegazy** [comment]
Thanks @mprobst!

**Comment by mprobst** [comment]
Re router, @btford can comment on that.

**Pull request merged**
